### ISSUE TITLE
don't print ANSI color codes when run in the browser

### ISSUE THREAD

**Issue by yoshuawuyts** [thlorenz/spok#1]
I sometimes use spok directly in the browser to test browser-specific code. It'd be cool if we could disable the ansi color code wrapping in the browser.

I was thinking using something like `localStorage.spokColors = false` instead of detecting it automatically so `tape-run` would still work without a problem.

Currently my output looks like this:

Reckon this is a good idea?

**Comment by yoshuawuyts** [comment]
<img width="948" alt="screen shot 2017-07-05 at 14 49 58" src="https://user-images.githubusercontent.com/2467194/27865119-a3aaf79c-6191-11e7-8eaf-dcd704768db1.png">

**Comment by yoshuawuyts** [comment]
Or alternatively: don't strip if running in electron, do strip if running in the browser. No manual interaction needed (:

**Comment by thlorenz** [comment]
Just do `spok.color = false` for your browser .. [it's configurable](https://github.com/thlorenz/spok/blob/master/spok.js#L96).

Open to any PRs that figure this out automagically, i.e. by looking for presence of global `window`.
But even in this case I should be able to override this to configure if I don't want colors on the server either for instance.

**Comment by yoshuawuyts** [comment]
cool! - yeah that's all I need :D

**Comment by thlorenz** [comment]
Hey just seeing this .. wouldn't mind a PR that does something like
```js
if (typeof window !== 'undefined') spok.color = false
```
but still allows you to override either way.

**Comment by thlorenz** [comment]
Unless you're good already then just please close please :)

**Comment by yoshuawuyts** [comment]
Oh no, yeah that'd be great! Im currently at an airport, so just pushing a
patch might work well perhaps — won't be behind my laptop until tomorrow
either way

**Comment by thlorenz** [comment]
OK, no rush ...
